import Head from 'next/head';
import { useRouter } from 'next/router';
import Link from 'next/link';
import PropTypes from 'prop-types';
import React, { useState } from 'react';

export default function Score({ allScores }) {
	const router = useRouter();
	const score_id = router?.query?.id || (router?.asPath ? router.asPath.split('/')[2] : undefined);
	const currentScore = allScores?.data?.find((score) => score._id === score_id) || {};

	const [formData, setFormData] = useState({
		chart: currentScore.chart || '',
		artist: currentScore.artist || '',
		charter: currentScore.charter || '',
		score: currentScore.score || '',
		percentage: currentScore.percentage || '',
		total_notes: currentScore.total_notes || '',
		notes_hit: currentScore.notes_hit || '',
		notes_missed: currentScore.notes_missed || '',
		best_streak: currentScore.best_streak || '',
		avg_multiplier: currentScore.avg_multiplier || '',
		overstrums: currentScore.overstrums || '',
	});

	const handleChange = (e) => {
		const { name, value } = e.target;
		setFormData((prev) => ({ ...prev, [name]: value }));
	};

	const handleUpdateScore = async (e) => {
		e.preventDefault();
		const updatedScore = {
			...formData,
			_id: currentScore._id || score_id,
		};

		await fetch('/api/scores', {
			method: 'PUT',
			headers: {
				'Content-Type': 'application/json',
			},
			body: JSON.stringify(updatedScore),
		});

		router.push(`/scores/${currentScore._id || score_id}`);
	};

	return (
		<>
			<Head>
				<title>{`Clone Hero Leaderboard - ${currentScore.chart || 'Edit Score'}`}</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<form onSubmit={handleUpdateScore}>
				<h1>Edit Score</h1>

				<label htmlFor="chart">Name </label>
				<input
					type="text"
					id="chart"
					name="chart"
					value={formData.chart}
					onChange={handleChange}
				/>
				<br />

				<label htmlFor="artist">Artist </label>
				<input
					type="text"
					id="artist"
					name="artist"
					value={formData.artist}
					onChange={handleChange}
				/>
				<br />

				<label htmlFor="charter">Charter </label>
				<input
					type="text"
					id="charter"
					name="charter"
					value={formData.charter}
					onChange={handleChange}
				/>
				<br />

				<label htmlFor="score">Score </label>
				<input
					type="text"
					id="score"
					name="score"
					value={formData.score}
					onChange={handleChange}
				/>
				<br />

				<label htmlFor="percentage">Percentage </label>
				<input
					type="text"
					id="percentage"
					name="percentage"
					value={formData.percentage}
					onChange={handleChange}
				/>
				<br />

				<label htmlFor="total_notes">Total Notes </label>
				<input
					type="text"
					id="total_notes"
					name="total_notes"
					value={formData.total_notes}
					onChange={handleChange}
				/>
				<br />

				<label htmlFor="notes_hit">Notes Hit </label>
				<input
					type="text"
					id="notes_hit"
					name="notes_hit"
					value={formData.notes_hit}
					onChange={handleChange}
				/>
				<br />

				<label htmlFor="notes_missed">Notes Missed </label>
				<input
					type="text"
					id="notes_missed"
					name="notes_missed"
					value={formData.notes_missed}
					onChange={handleChange}
				/>
				<br />

				<label htmlFor="best_streak">Best Streak </label>
				<input
					type="text"
					id="best_streak"
					name="best_streak"
					value={formData.best_streak}
					onChange={handleChange}
				/>
				<br />

				<label htmlFor="avg_multiplier">Average Multiplier </label>
				<input
					type="text"
					id="avg_multiplier"
					name="avg_multiplier"
					value={formData.avg_multiplier}
					onChange={handleChange}
				/>
				<br />

				<label htmlFor="overstrums">Overstrums </label>
				<input
					type="text"
					id="overstrums"
					name="overstrums"
					value={formData.overstrums}
					onChange={handleChange}
				/>
				<br />

				<button type="submit">Submit</button>
				<Link href={`/scores/${currentScore._id || score_id}`}>Back</Link>
			</form>
		</>
	);
}

Score.propTypes = {
	allScores: PropTypes.object.isRequired,
};

export { getScoresServerSideProps as getServerSideProps } from '../../../../lib/getScoresProps';
