import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import React from 'react'
import { Table } from '@nextui-org/react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
	return (
		<>
			<Head>
				<title>Clone Hero Leaderboard</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1 className={styles.title}>
				<span style={{ fontFamily: inter.style.fontFamily }}>
					Clone Hero Leaderboard
				</span>
			</h1>
			<Table
				bordered
				shadow={false}
				aria-label="Example table with static content"
				css={{
					height: "auto",
					minWidth: "100%",
				}}
				selectionMode="single"
				>
				<Table.Header>
					<Table.Column>CHART</Table.Column>
					<Table.Column>ARTIST</Table.Column>
					<Table.Column>CHARTER</Table.Column>
					<Table.Column>NOTES HIT</Table.Column>
					<Table.Column>TOTAL NOTES</Table.Column>
				</Table.Header>
				<Table.Body>
					<Table.Row key="1">
						<Table.Cell>A Cruel Angel&apos;s Thesis</Table.Cell>
						<Table.Cell>331Erock</Table.Cell>
						<Table.Cell>Teffy</Table.Cell>
						<Table.Cell>1,028</Table.Cell>
						<Table.Cell>1,132</Table.Cell>
					</Table.Row>
				</Table.Body>
			</Table>
		</>
	)
}
