import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { Inter } from 'next/font/google';
import { useRouter } from 'next/router';
import Link from 'next/link';
import PropTypes from 'prop-types';
import React from 'react';

const inter = Inter({ subsets: ['latin'] });

export default function Score({ allScores }) {
	const router = useRouter();
	const score_id = router?.query?.id || (router?.asPath ? router.asPath.split('/')[2] : undefined);
	const currentScore = allScores?.data?.find((score) => score._id === score_id);

	if (!currentScore) {
		return (
			<>
				<Head>
					<title>Clone Hero Leaderboard - Score Not Found</title>
				</Head>
				<h1>Score Not Found</h1>
				<Link href="/">Back</Link>
			</>
		);
	}

	return (
		<>
			<Head>
				<title>{`Clone Hero Leaderboard - ${currentScore.chart}`}</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1 className={styles.title}>
				<span style={{ fontFamily: inter.style.fontFamily }}>
					{currentScore.chart}
				</span>
			</h1>
			<h2>
				<span style={{ fontFamily: inter.style.fontFamily }}>
					Artist: {currentScore.artist}
				</span>
			</h2>
			<h3>
				<span style={{ fontFamily: inter.style.fontFamily }}>
					Charter: {currentScore.charter}
				</span>
			</h3>
			<h3>
				<span style={{ fontFamily: inter.style.fontFamily }}>
					Score: {currentScore.score}
				</span>
			</h3>
			<h3>
				<span style={{ fontFamily: inter.style.fontFamily }}>
					Percentage: {currentScore.percentage}
				</span>
			</h3>
			<h3>
				<span style={{ fontFamily: inter.style.fontFamily }}>
					Total Notes: {currentScore.total_notes}
				</span>
			</h3>
			<h3>
				<span style={{ fontFamily: inter.style.fontFamily }}>
					Notes Hit: {currentScore.notes_hit}
				</span>
			</h3>
			<h3>
				<span style={{ fontFamily: inter.style.fontFamily }}>
					Notes Missed: {currentScore.notes_missed}
				</span>
			</h3>
			<h3>
				<span style={{ fontFamily: inter.style.fontFamily }}>
					Best Streak: {currentScore.best_streak}
				</span>
			</h3>
			<h3>
				<span style={{ fontFamily: inter.style.fontFamily }}>
					Average Multiplier: {currentScore.avg_multiplier}
				</span>
			</h3>
			<h3>
				<span style={{ fontFamily: inter.style.fontFamily }}>
					Overstrums: {currentScore.overstrums}
				</span>
			</h3>

			<Link href={`/scores/${currentScore._id}/edit`}>Edit</Link>
			<Link href="/">Back</Link>
		</>
	);
}

Score.propTypes = {
	allScores: PropTypes.object.isRequired,
};

export { getScoresServerSideProps as getServerSideProps } from '../../../lib/getScoresProps';
