import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Inter } from 'next/font/google'
import { useRouter } from 'next/router'
import Link from 'next/link'
// import Image from 'next/image'
import PropTypes from 'prop-types'

const inter = Inter({ subsets: ['latin'] })

export default function Score({ allScores }) {
	const router = useRouter();
	const score_id = router.asPath.split('/')[2];
	return (
		<>
			<Head>
				<title>{`Clone Hero Leaderboard - ${allScores.data.find((score) => score._id === score_id).chart}`}</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1 className={styles.title}>
				<span style={{ fontFamily: inter.style.fontFamily }}>
					{allScores.data.find((score) => score._id === score_id).chart}
				</span>
			</h1>
			<h2>
				<span style={{ fontFamily: inter.style.fontFamily }}>
					Artist: {allScores.data.find((score) => score._id === score_id).artist}
				</span>
			</h2>
			<h3>
				<span style={{ fontFamily: inter.style.fontFamily }}>
					Charter: {allScores.data.find((score) => score._id === score_id).charter}
				</span>
			</h3>
			<h3>
				<span style={{ fontFamily: inter.style.fontFamily }}>
					Score: {allScores.data.find((score) => score._id === score_id).score}
				</span>
			</h3>
			<h3>
				<span style={{ fontFamily: inter.style.fontFamily }}>
					Percentage: {allScores.data.find((score) => score._id === score_id).percentage}
				</span>
			</h3>
			<h3>
				<span style={{ fontFamily: inter.style.fontFamily }}>
					Total Notes: {allScores.data.find((score) => score._id === score_id).total_notes}
				</span>
			</h3>
			<h3>
				<span style={{ fontFamily: inter.style.fontFamily }}>
					Notes Hit: {allScores.data.find((score) => score._id === score_id).notes_hit}
				</span>
			</h3>
			<h3>
				<span style={{ fontFamily: inter.style.fontFamily }}>
					Notes Missed: {allScores.data.find((score) => score._id === score_id).notes_missed}
				</span>
			</h3>
			<h3>
				<span style={{ fontFamily: inter.style.fontFamily }}>
					Best Streak: {allScores.data.find((score) => score._id === score_id).best_streak}
				</span>
			</h3>
			<h3>
				<span style={{ fontFamily: inter.style.fontFamily }}>
					Average Multiplier: {allScores.data.find((score) => score._id === score_id).avg_multiplier}
				</span>
			</h3>
			<h3>
				<span style={{ fontFamily: inter.style.fontFamily }}>
					Overstrums: {allScores.data.find((score) => score._id === score_id).overstrums}
				</span>
			</h3>

			{/* <Image src={???} alt={allScores.data.find((score) => score._id === score_id).chart} width={300} height={300} /> */}

			<Link href={`/scores/${allScores.data.find((score) => score._id === score_id)._id}/edit`}>Edit</Link>
			<Link href={`/`}>Back</Link>
		</>
	)
}

Score.propTypes = {
	allScores: PropTypes.object.isRequired,
};

export async function getServerSideProps() {
	let res = await fetch(process.env.BASE_URL + '/api/scores', {
		method: 'GET',
		headers: {
			'Content-Type': 'application/json'
		},
	});
	let allScores = await res.json();

	return {
		props: { allScores },
	};
}
